### ISSUE TITLE
Stack size fixed

### ISSUE THREAD

**Issue by fjrg76-com** [wditch/plcLib#11]
In the AndBlock.ino example you asume that a 32 level depth for a stack is correct. What if I need more or less than such quantity? Magic numbers are almost forbidden in programming. The libraries client should choose the figure that fits the most his/her application.

I'm going to write my own PLC library, and I found yours while looking for the state of art in this matter. I noticed several flows while studying it, as the aforementioned comment. Will you accept my advices? I'm a professional embedded sytem programer in C++.

**Comment by wditch** [comment]
Firstly, good luck if you decide to write your own library.

My motivation for writing the library was primarily to demonstrate how easy it is to write a PLC style library, so essentially it is a proof of concept, rather than an attempt to develop a commercial quality or standards compliant application. There are a few things I would do differently if starting from scratch, although the stack feature is not one of them.

The purpose of the stack feature is to allow solution of complex block logic circuits, where the temporary result of a branch needs to be stored and later retrieved. This requires storage of single bit values.

The '32 levels' you refer to is actually the word size of the longest integer variable type directly supported by the Arduino Uno (Long). The stack operates by storing individual bits into this variable, so the equivalent of a microprocessor stack pointer register is created as the bit position within this data word. As a design it is relatively efficient, allowing a 32 level stack to be created using only 4 bytes of RAM. The algorithm for storing and retrieving values is also straightforward.

While I could have written a more general purpose stack, in which the user made choices regarding data size and stack size, I chose not to since the Arduino Uno has only 2k of SRAM. Poor stack design by a user could have impacted on system performance.
